   # docker-compose.yaml
   version: '3.8'
   services:
     jenkins:
       image: jenkins/jenkins:lts
       container_name: jenkins
       privileged: true
       user: root
       ports:
          - 8090:8080
          - 50000:50000
       volumes:
          - ./jenkins_configuration:/var/jenkins_home
          - /var/run/docker.sock:/var/run/docker.sock