server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/test
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      show:
        sql: true